#!/bin/bash
cd /tmp
mkdir $HOME/.fabric-repo
mkdir -p  go/src/github.com/hyperledger
tar -xzvf $HOME/.fabric-repo/fabric-repo.tar.gz -C /tmp
cd go/src/github.com/hyperledger
git clone https://github.com/hyperledger/fabric-ca.git

export GOPATH=/tmp/go
git clone https://github.com/hyperledger/fabric.git
git clone https://github.com/hyperledger/fabric-cli.git

cd fabric
git checkout release-1.4
make release

cd ../fabric-ca
git checkout release-1.4
make fabric-ca-server fabric-ca-client

cd ../fabric-cli
make


sudo mkdir -p /usr/lib/hyperledger/fabric
sudo mkdir -p /usr/lib/hyperledger/fabric-ca
sudo mkdir -p /usr/lib/hyperledger/fabric-cli

sudo cp -r /tmp/go/src/github.com/hyperledger/fabric/release/linux-amd64  /usr/lib/hyperledger/fabric/release-1.4
sudo cp -r /tmp/go/src/github.com/hyperledger/fabric-ca/bin/*  /usr/lib/hyperledger/fabric/release-1.4/bin/
sudo cp -r /tmp/go/src/github.com/hyperledger/fabric-cli/bin/*  /usr/lib/hyperledger/fabric-cli/bin/

sudo ln -s /usr/lib/hyperledger/fabric/release-1.4/bin/* /usr/lib/hyperledger/fabric/bin
sudo ln -s /usr/lib/hyperledger/fabric-ca/release-1.4/bin/* /user/lib/hyperledger/fabric-ca/bin

sudo echo "## HYPERLEDGER PATHS"
sudo echo "export PATH=/usr/lib/hyperledger/fabric/bin:${PATH}" >> /etc/profile
sudo echo "export PATH=/usr/lib/hyperledger/fabric-ca/bin:${PATH}" >> /etc/profile
sudo echo "export PATH=/usr/lib/hyperledger/fabric-cli/bin:${PATH}" >> /etc/profile
sudo echo "export FABRIC_CA_SERVER_HOME=/home/hyperledger/fabric-ca/server" >> /etc/profile
sudo echo "export FABRIC_CA_CLIENT_HOME=/home/hyperledger/fabric-ca/client" >> /etc/profile
sudo echo "export FABRIC_CFG_PATH=/home/hyperledger/config" >> /etc/profile
mkdir -p $FABRIC_CA_SERVER_HOME
mkdir -p $FABRIC_CA_CLIENT_HOME
mkdir -p $FABRIC_CFG_PATH
